version: "3.3"
services:
  backend:
    build: my-backend
    container_name: backend
    restart: always
    secrets:
      - db-password 
    networks:
      - frontend-backend
      - backend-mysql
    depends_on:
      - db
    ports:
      - "5271:5271"
    expose:
      - 5271
  db:
    build: db
    container_name: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=morpheus
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - backend-mysql
    ports:
      - "3306:3306"
  frontend:
    build: frontend-app
    container_name: frontend
    ports: 
      - "8080:80"
    volumes:
      - ./frontend-app/src:/code/src
      - /project/node_modules
    networks:
      - frontend-backend
    depends_on:
      - backend
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-mysql: {}
  frontend-backend: {}