version: "3"
services:
  backend:
    build: my-backend
    restart: always
    secrets:
      - db-password 
    networks:
      - angular-dotnetcore_web_api
      - dotnetcore_web_api-mysql
    depends_on:
      - db
    expose:
      - 5271
  db:
    build: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=morpheus
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - dotnetcore_web_api-mysql
  frontend:
    build: frontend-app
    ports:
      - 8080:80
    volumes:
      - ./frontend-app/src:/code/src
      - /project/node_modules
    networks:
      - angular-dotnetcore_web_api
    depends_on:
      - backend
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  angular-dotnetcore_web_api: {}
  dotnetcore_web_api-mysql: {}