name: virtual_dev_env_simple-determined_tesla
services:
  backend:
    build:
      context: C:\repos\dockerfun_simple\virtual_dev_env_simple\my-backend
      dockerfile: Dockerfile
      target: final
    command:
    - infinity
    depends_on:
      db:
        condition: service_started
    entrypoint:
    - sleep
    expose:
    - "5271"
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: virtual_dev_env_simple-determined_tesla
    networks:
      backend-mysql: null
      frontend-backend: null
    ports:
    - mode: ingress
      target: 5271
      published: "5271"
      protocol: tcp
    restart: always
    stop_signal: SIGKILL
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
    - type: bind
      source: C:\repos\dockerfun_simple\virtual_dev_env_simple
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-virtual_dev_env_simple-determined_tesla-backend
      target: /home/vscode
  db:
    build:
      context: C:\repos\dockerfun_simple\virtual_dev_env_simple\db
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: morpheus
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    expose:
    - "3306"
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: virtual_dev_env_simple-determined_tesla
    networks:
      backend-mysql: null
    ports:
    - mode: ingress
      target: 3306
      published: "3306"
      protocol: tcp
    restart: always
    secrets:
    - source: db-password
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  frontend:
    build:
      context: C:\repos\dockerfun_simple\virtual_dev_env_simple\frontend-app
      dockerfile: Dockerfile
    depends_on:
      my-backend:
        condition: service_started
    expose:
    - "80"
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: virtual_dev_env_simple-determined_tesla
    networks:
      frontend-backend: null
    ports:
    - mode: ingress
      target: 80
      published: "8080"
      protocol: tcp
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
networks:
  backend-mysql:
    name: virtual_dev_env_simple-determined_tesla_backend-mysql
  default:
    name: virtual_dev_env_simple-determined_tesla_default
  frontend-backend:
    name: virtual_dev_env_simple-determined_tesla_frontend-backend
volumes:
  db-data:
    name: virtual_dev_env_simple-determined_tesla_db-data
  vsCodeServerVolume-virtual_dev_env_simple-determined_tesla-backend:
    name: vsCodeServerVolume-virtual_dev_env_simple-determined_tesla-backend
secrets:
  db-password:
    name: virtual_dev_env_simple-determined_tesla_db-password
    file: C:\repos\dockerfun_simple\virtual_dev_env_simple\db\password.txt
