version: "3.7"
services:
  my-backend:
    build:
      context: my-backend
    restart: always
    secrets:
      - db-password
    environment:
      MYSQL_HOST: db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - angular-dotnetcore_web_api
      - dotnetcore_web_api-mysql
    depends_on:
      - db
  db:
    build:
      context: db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=morpheus
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
    networks:
      - dotnetcore_web_api-mysql
  frontend-app:
    build:
      context: frontend-app
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - angular-dotnetcore_web_api
    depends_on:
      - my-backend
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  angular-dotnetcore_web_api: {}
  dotnetcore_web_api-mysql: {}
